# fly.toml app configuration file generated for elia-backend-golang on 2024-03-27T10:17:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elia-backend-golang'
primary_region = 'ams'

[build]
  [build.args]
    GO_VERSION = '1.22.1'

[env]
  PORT = '80'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
