version: "3.7"

services:
  golang:
    build:
      context: ./golang/
      dockerfile: ./Dockerfile
    tty: true # colorized output
    ports:
      - 80:80
  steering-python:
    network_mode: "host"
    build:
      context: ./steering-python/
      dockerfile: ./Dockerfile
    tty: true # colorized output
    ports:
      - 5001:5001