version: "3.7"

services:
  golang:
    build:
      context: ./golang/
      dockerfile: ./Dockerfile
    tty: true # colorized output
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: ghcr.io/inthepocket/elia-hackathon-2024-backend/elia-hackathon-backend-golang:latest
  steering-python:
    network_mode: "host"
    build:
      context: ./steering-python/
      dockerfile: ./Dockerfile
    tty: true # colorized output
    ports:
      - 5001:5001
    image: ghcr.io/inthepocket/elia-hackathon-2024-backend/elia-hackathon-backend-steering-python:latest
